version: '3.4'

services:
  app:
    image: juliocesarmidia/graphql-course-app:latest
    build:
      context: .
    command: 'sh -c "yarn install && yarn run dev"'
    container_name: app
    hostname: app
    environment:
      NODE_ENV: development
      APP_AUTH_SECRET: ${APP_AUTH_SECRET}
      APP_HOST: ${APP_HOST:-0.0.0.0}
      APP_PORT: ${APP_PORT:-4000}
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASS: ${DATABASE_PASS:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-graphql_course}
    networks:
      - subnet_0
    restart: on-failure
    ports:
      - 4000:4000
    volumes:
      - ./:/app:rw
      - app-node-modules:/app/node_modules:rw

  migrations:
    image: juliocesarmidia/graphql-course-migrations:latest
    build:
      context: infrastructure/database/knex/
    command: '--knexfile=knexfile.js --env development migrate:latest'
    container_name: migrations
    hostname: migrations
    environment:
      NODE_ENV: development
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASS: ${DATABASE_PASS:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-graphql_course}
    networks:
      - subnet_0
    restart: "no"
    volumes:
      - ./infrastructure/database/knex/:/app:rw
      - migrations-node-modules:/app/node_modules:rw

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-graphql_course}
    networks:
      - subnet_0
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/database/init.sql:/docker-entrypoint-initdb.d/init.sql:rw
      - postgres-data:/var/lib/postgresql/data:rw

networks:
  subnet_0:
    driver: bridge

volumes:
  app-node-modules: {}
  migrations-node-modules: {}
  postgres-data: {}
