version: '3.4'

services:
  api:
    image: juliocesarmidia/graphql-course-api:latest
    build:
      context: api/
    command: 'sh -c "yarn install && yarn run dev"'
    container_name: api
    hostname: api
    environment:
      NODE_ENV: development
      API_AUTH_SECRET: ${API_AUTH_SECRET}
      API_HOST: ${API_HOST:-0.0.0.0}
      API_PORT: ${API_PORT:-4000}
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASS: ${DATABASE_PASS:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-graphql_course}
    networks:
      - subnet_0
    restart: on-failure
    ports:
      - 4000:4000
    volumes:
      - ./api/:/app:rw
      - api-node-modules:/app/node_modules:rw

  client:
    image: juliocesarmidia/graphql-course-client:latest
    build:
      context: client/
      dockerfile: Development.Dockerfile
    container_name: client
    hostname: client
    environment:
      NODE_ENV: development
    networks:
      - subnet_0
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./client/:/app:rw
      - ./client/nginx.conf:/etc/nginx/nginx.conf
      - client-node-modules:/app/node_modules:rw

  migrations:
    image: juliocesarmidia/graphql-course-migrations:latest
    build:
      context: api/infrastructure/database/knex/
    command: '--knexfile=knexfile.js --env development migrate:latest'
    container_name: migrations
    hostname: migrations
    environment:
      NODE_ENV: development
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASS: ${DATABASE_PASS:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-graphql_course}
    networks:
      - subnet_0
    restart: "no"
    volumes:
      - ./api/infrastructure/database/knex/:/app:rw
      - migrations-node-modules:/app/node_modules:rw

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-graphql_course}
    networks:
      - subnet_0
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./api/infrastructure/database/init.sql:/docker-entrypoint-initdb.d/init.sql:rw
      - postgres-data:/var/lib/postgresql/data:rw

networks:
  subnet_0:
    driver: bridge

volumes:
  api-node-modules: {}
  client-node-modules: {}
  migrations-node-modules: {}
  postgres-data: {}
